### ISSUE TITLE
[Minor usability bug] Changing the location need a restart of WelkWeer to take effect

### ISSUE THREAD

**Issue by Olf0** [a-dekker/welkweer#1]
Issue description: Changes to Instellingen-->Locatie need a restart of WelkWeer to take effect for the local weather maps. 

Expected behaviour: Changing the location takes effect when leaving the settings ("Instellingen") page or when entering the local weather (via "Lokaal" button), as it is already the case for Instellingen-->Zoomniveau lokaal (i.e. that setting works as expected). 

Tested with WelkWeer 0.8-3 from Warehouse under SailfishOS 2.1.0.11

P.S.: It took me a while to understand (presumably others as well), that the location setting actually works, as it appears to be defunct on first sight. 

Kudos to you @a-dekker for this cool SailfishOS app.

**Comment by a-dekker** [comment]
Could very well be, I do not change my location that often ;-)
Will have a look at it and see if it easy to modify the behavior.

**Comment by a-dekker** [comment]
I don't need a restart of the app.

When I change the location in "Instellingen" and return to to mainpage, you are faced with the old location. I could force a refresh here. But as soon as I choose "Vernieuwen", all data is renewed/updated, including the "Lokaal" map location.

**Comment by Olf0** [comment]
> I don't need a restart of the app. 
> When I change the location in "Instellingen" and return to to mainpage, you are faced with the old location. [...] But as soon as I choose "Vernieuwen", all data is renewed/updated, including the "Lokaal" map location.

Oh, I did not realise, that the textual data in WelkWeer's main page is also incorrect (i.e. the data for the former location) after changing Instellingen-->Locatie. 
And yes, refreshing the weather data with "Vernieuwen" in the pulley menu updates the data with the one for the new location then (in the main page as well as in the Lokaal page).

> I could force a refresh here. 

Agreed, "refresh the weather data after changing the location" (or "refresh the weather data when leaving the Instellingen page"; actually a refresh is only needed, when both aforementioned conditions are true) describes a solution to this issue much more precisely than my first try.  
Thank you for considering this.

**Comment by a-dekker** [comment]
The latest commit should lead to an update in case one of the settings has been changed (v 0.8.4 on openrepos.net)

**Comment by Olf0** [comment]
Thanks a lot, working nicely. :))
(Wow, you were quick, despite the additional small changes in commit #20d9d8ba9ea9cc39b0a0144890b252ee6f834b95).

**Comment by Olf0** [comment]
Side note (after looking through the changes to the code): For some reason changing the zoom level already took effect without manual refreshing (as already mentioned), before introducing the if-clauses with `mainapp.settingsChanged = true`in each `case` of `switch (zoomlevel.currentIndex)` (i.e. with WelkWeer 0.8-3). 

Edit: Retested (to be sure) with 0.8-3 on my second Jolla phone. Yes, it did, triggering a refresh was not necessary (so are these specific changes, presumably).
