### ISSUE TITLE
[Minor visual issues] Unnecessary vertical scrolling of some windows etc.

### ISSUE THREAD

**Issue by Olf0** [a-dekker/welkweer#2]
Dear Arno,

a really minor usability issue was introduced into Welkweer sometime between version 0.8-0 and 0.11-0 on Jolla 1 phones in landscape orientation (tested under SailfishOS 2.1.3.7): A couple of windows are a little too high (just a few pixels), so they became vertically scrollable, which is slightly irritating.
Affected windows:
- Main window
- About
- Local (independent of the zoom level)
- And since v0.11-1 or -2: 5 day forecast (was O.K. up to v0.11-0)
- In contrast to these, all other windows are fine.

Side note: In the main window there are two other visual nuisances (also *only* in landscape orientation, observed on a Jolla 1 phone), which even less important IMO.
- The large local weather station name "XYZ" collides vertically with the text line "Meetstation XYZ" beneath it.  IMO, one of those two text line could just be eliminated.
- The button labels "Weer morgen NL" and "Neerslag (->2uur)" are larger than the buttons proper and collide horizontally and the button label "Temperatuur NL" is slightly larger than its button.  I don't know, if anything can be done about this, technically.

All this does not affect any functionality, but the visual appearance of WelkWeer has been better in the past WRT the scrolling issue (the primary one reported here).

And many kudos to you for creating and maintaining WelkWeer and your numerous other nice SailfishOS apps (plus taking care about UnitConverter).

Example screenshots: 
- Main window scrolled down (default): ![screenshot_20171221_009](https://user-images.githubusercontent.com/16547876/34275418-83b0deac-e69d-11e7-92e7-06c6caacb584.png)
- Main window scrolled up: ![screenshot_20171221_003](https://user-images.githubusercontent.com/16547876/34275227-9cea0f3e-e69c-11e7-8c4e-f841fb2e6c7b.png)
- Local weather scrolled down (default): ![screenshot_20171221_008](https://user-images.githubusercontent.com/16547876/34275438-972a0b3e-e69d-11e7-9f06-ae4bd940eddb.png)
- Local weather scrolled up: ![screenshot_20171221_005](https://user-images.githubusercontent.com/16547876/34275347-2e4b87d2-e69d-11e7-8f52-6782374a4a7a.png)

**Comment by a-dekker** [comment]
Hi Olf,

In recent Sailfish OS versions you can change the Text size in settings (Normal/Large/Huge). I suspect you use large or huge, because it all does fit on my Jolla 1 using normal text size.

It is a bit cramped to display all info in landscape, so the "Meetstation" does touch the city name, but that does not really bother me.

The local weather is a difficult one. It is just a webview that I can zoom in to with certain steps, so picture perfect projecting is very hard with the different screen ratios and resolutions.

**Comment by Olf0** [comment]
@a-dekker, thanks for the quick reply, with which I only partially concur.

a. Ah, yes I use "Large" out of {Normal, Large, Huge}.

b. Isn't the Meetstation *XYZ* always identical to to the city name *XYZ*?  If they are, one of them is superfluous and can be omitted; my suggestion would be to display "Meetstation XYZ" instead of "XYZ" with the same attributes (size, position), which the city name "XYZ" currently has.
This would also eliminate the scrolling a few pixels up and down (by using less vertical space) of the main window, plus would provide sufficient space for the last line "Last updated on ..." to become *fully* visible (which currently never really is the case, even when scrolling up as far as possible).

c1. Understood for the local weather, even though I still wonder why other images from Buienradar (Neerslag NL, Buien Europa) fit so perfectly.
Also note, that the "waiting spinner" (when loading the local weather) is initially displayed way too far up, but is vertically centered a moment later.  Something is (done) quite different here (i.e. between "Lokaal" and "Neerslag NL" / "Buien Europa") WRT the positioning and scaling of the retrieved images; and when loading them (bar graph vs. spinner).

c2.  But this reason does not cover the "little vertical scrolling issue" in the "Over (About)"-, "5 day forecast (text only)"- and main window (mostly text) at all.
 Especially as the "little vertical scrolling" was just recently introduced into the "5 day forecast"-window.

**Comment by a-dekker** [comment]
b. 
No it isn't. For Amsterdam it is "Meetstation Schiphol" for example. If you live in the north of Amsterdam it is good to know the data is from there I think.

c1.
The other images are all png files or animated gifs and not webviews, which makes them very different.

c2.
It could be the header in the 5 day forecast is a bit bigger font now on the Jolla 1, I will check. Same goes for the About, although I can't recall any changes there.
Remember that it's all okay using the normal fontsize. If someone wants bigger font it is their choice, but be prepared that some layouts may break.

**Comment by Olf0** [comment]
b. Absolutely, that is why my suggestion was to just display "Meetstation Schiphol", as this is obvious when one does the location selection ("Amsterdam (Schiphol)" in this case).

c2. Well, I have been using the "Large" font setting since it has been available in SailfishOS and have not observed layout breakages yet, except for in WelkWeer.  OTOH, other applications do not have to cram so much information (and hence text) on their windows.

**Comment by a-dekker** [comment]
Made some changes in 0.11-3, so landscape main screen and forecast should also fit (without scrolling) having a large font on jolla 1.

**Comment by Olf0** [comment]
Thank you very much!

Cheers & happy coding.

**Comment by Olf0** [comment]
Being nosy, I took a look at what you have done in commit 482a58424222f39ea7cbb06789c09d6081cbe99b: This is looking good!

BTW, if you should ever decide to offer alternative languages to NL in WelkWeer (EN, DE and FR would be obvious candidates IMO), I am sure willing to support you, if you set up a transifex project for it (although I am quite happy about having to read a little Dutch, when using it).  But I am aware that this would require a separate language setting in WelkWeer, as Dutch still is not a language officialy supported by SailfishOS (but it seems to be on the way, looking at https://together.jolla.com/question/134467/official-announcement-translate-sailfish-os-elections-of-community-languages-linguists/, although at "Jolla speed" ;\ ).

**Comment by a-dekker** [comment]
Using Qt5 Linguist you could create your own language files, but given the very small user base potential for this and English not being the source language, I rather avoid the subject :-)
