### ISSUE TITLE
Normale Buienradar CurrentWeather laadt niet meer

### ISSUE THREAD

**Issue by cow-n-berg** [a-dekker/welkweer#5]
Beste Arno,

Sinds een paar dagen kan ik de buienradar zelf niet meer zien in de app, de andere kaarten en overzichten doen het nog wel.

Ik vermoed dat de code in CurrentWeather.qml staat. Als ik de url probeer, krijg ik de melding dat de variabele "stream" niet null mag zijn. Het bruutweg afkorten van de url tot https://image.buienradar.nl/2.0/image/animation/RadarMapRainNL leidt wel tot bewegende plaatjes, met een aangepaste url https://image-cdn.buienradar.nl/br-processing/image-api/RadarMapRainNL/Animation/202007050905__550x512_True_False_True_3_3_1_0_0.gif.

Misschien lukt het me zelf te compileren en testen, is nog niet gebeurd.

Groeten, Rob

**Comment by a-dekker** [comment]
Hoi Rob,

Ik weet van het probleem, maar omdat buienradar.nl in het verleden wel eens vaker kort iets niet beschikbaar had wilde ik nog even wachten of het hersteld wordt. Ik vermoed van niet, omdat het al enige dagen speelt.
De aangepaste url die jij noemt is overigens niet van de komende 3 uur, maar de huidige situatie. De 3 uurs voorspelling lijkt nog wel te bestaan, alleen kan ik die niet rechtstreeks op buienrader zelf localiseren.

**Comment by cow-n-berg** [comment]
Hoi Arno,

De background image van de voorpagina van de site is https://image-cdn.buienradar.nl/br-processing/image-api/RadarMapRainNL/Sprite/202007050935__550x512_False_False_True_0_12_0_0_0.png

202007050935 komt niet zo heel nauw, laatste twee hh:mm mag niet groter zijn dan nu + 5 minuten, en dan in UTC.

Op de homepage van de site lijken de beelden opgebouwd te zijn uit lagen.
https://image.buienradar.nl/2.0/image/single/RadarMapRainWebmercatorNL?extension=png&width=1058&height=915&renderText=True&renderBranding=True&renderBackground=True&timestamp=202007051030
waarbij drie maal False wordt gebruikt ipv mijn poging True. Met True krijg je het plaatje dat je wilt hebben, inclusief tijdstip, maar helaas slechts een van de twaalf.

Ze lijken de beelden Single of Sprite te gebruiken.

https://image.buienradar.nl/2.0/image/sprite/RadarMapRainWebmercatorNL?extension=png&width=1058&height=915&renderText=True&renderBranding=True&renderBackground=True&history=0&forecast=12&skip=0&timestamp=202007050935

duurt even maar dan heb je wel wat je zoekt?

**Comment by cow-n-berg** [comment]
https://image.buienradar.nl/2.0/image/sprite/RadarMapRainWebmercatorNL?extension=png&width=550&height=512&renderText=True&renderBranding=False&renderBackground=True&history=0&forecast=12&skip=0
doet het ook, lijkt iets sneller. Timestamp lijkt niet nodig.

Conclusie: het lijkt erop dat gewoon het verzoek om een forecast van 36 te veel is.
http://api.buienradar.nl/image/1.0/radarmapnl/gif/?hist=0&forc=12&width=550&l=1&step=1

Groeten, Rob

**Comment by a-dekker** [comment]
Ik maak gebruik van animated GIF's. Overstappen naar een statische PNG bestand met diverse beelden is dan wel een hele andere manier van benaderen wat de nodige aanpassingen zal vragen. Iets waar ik op dit moment de toegevoegde waarde nog niet van zie.

**Comment by cow-n-berg** [comment]
Deze aanpassing heb ik gecompileerd, en werkt op mijn XA2:
http://api.buienradar.nl/image/1.0/radarmapnl/gif/?hist=0&forc=12&width=550&l=1&step=1
ipv
http://api.buienradar.nl/image/1.0/radarmapnl/gif/?hist=0&forc=36&width=550&l=1&step=1

Wellicht lost het probleem zich inderdaad binnenkort op, als Buienradar erachter komt dat er weinig forecast is.

Groeten, Rob

**Comment by a-dekker** [comment]
Ik ben maar naar de 1 uurs voorspelling gegaan. 3 uur is is toch al minder betrouwbaar.
