### ISSUE TITLE
Weerdata voor Rotterdam wordt niet meer geladen

### ISSUE THREAD

**Issue by dyraig** [a-dekker/welkweer#6]
Sinds een paar dagen krijg ik geen weerdata meer als ik onder "Instellingen" als locatie "Rotterdam" kies. "Rotterdam Haven" lijkt wel te werken, maar dan zonder temperatuur. Andere plaatsen zoals Amsterdam of Eindhoven werken wel.

Versie: 0.23.-3
SailfishOS 4.1.0.24

**Comment by a-dekker** [comment]
Volgens mij is het probleem al weer weg?

Het ging alleen bij een eerdere poging mis bij mij. Oorzaak leek het ontbreken van de windrichting info, waar de app niet lekker mee omgaat. Dat kan ik misschien nog wel verbeteren.

**Comment by dyraig** [comment]
Je hebt gelijk - net weer geprobeerd en nu werkt het weer. In elk geval de hele dag gisteren ging het mis. Maar goed, dan is er dus toch geen probleem. Bedankt voor het nakijken!
