### ISSUE TITLE
Toevoegen van een weerwaarschuwing notificatie

### ISSUE THREAD

**Issue by mar1ad** [a-dekker/welkweer#7]
Recent hebben we een aantal weerwaarschuwingen achter elkaar gehad.
De laatste storm waarschuwing heb ik compleet gemist en werd er wel door overvallen.

**Comment by a-dekker** [comment]
Dat is in versie 0.24-1 toegevoegd, al voor de laatste serie waarschuwingen.
Welkweer moet wel opgestart zijn om dat te kunnen zien. Misschien gebruik je de versie uit de Jolla store? Deze loopt achter op de versie in openrepos.net en bevat deze functionaliteit niet.

**Comment by mar1ad** [comment]
Ik heb 0.24-2 geinstalleerd staan. Het was me wel opgevallen dat er een waarschuwingsicoon voor de waarschuwingen stond, maar geeft die ook een dbus melding naar Lipstick? Zodat je bij de Sailfish Notifications een melding krijgt?

**Comment by a-dekker** [comment]
Nee, dat heb ik bewust niet gedaan. Ik vind/vond het waarschuwingsicoon voldoende, ik zit zelf niet te wachten om elke keer dat ik WelkWeer opstart weer een los bericht te krijgen als er de komende 3 dagen een alert komt. Op een bepaald moment weet ik dat wel.
Maar ik zag inmiddels dat je een PR had gemaakt, waarbij een notificatie richting SailfishOS aan of uit te zetten is. Dan heb ik niet zoveel bezwaar tegen een dergelijke aanpassing.

**Comment by mar1ad** [comment]
Dat kan ik me heel goed voorstellen, daarom staat de optie ook default uit ;-)

Ik zat er ook nog aan te denken om het mogelijk in te stellen op alert nivo, bijvoorbeeld alleen een notificatie vanaf oranje.

**Comment by a-dekker** [comment]
Zie maar even :-) Ik zal het vandaag nog even testen en dan een nieuwe release maken.

Dank voor je bijdrage!
